import pandas as pd
import json
import sys
import glob

def load_json_to_dataframe(file_path):
    """
    Loads a JSON file generated by table_extractor.py into a pandas DataFrame.

    Args:
        file_path (str): The path to the JSON file.

    Returns:
        pandas.DataFrame: The loaded DataFrame, or None if an error occurs.
    """
    print(f"--- Processing file: {file_path} ---")
    try:
        with open(file_path, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: File not found at '{file_path}'")
        return None
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from '{file_path}'")
        return None

    if 'rows' not in data or not data['rows'] or len(data['rows']) < 2:
        print("Warning: JSON file does not contain enough rows to form a header and data. Skipping.")
        return None

    # Extract the text from each cell for the header and data
    all_rows_text = [[cell['text'] for cell in row['cells']] for row in data['rows']]

    # Use the first row as header, the rest as data
    header = all_rows_text[0]
    data_rows = all_rows_text[1:]

    # Create the DataFrame
    df = pd.DataFrame(data_rows, columns=header)

    return df

if __name__ == "__main__":
    # Find all table*.json files in the current directory
    json_files = sorted(glob.glob('table_*.json'))

    if not json_files:
        print("No 'table_*.json' files found in the current directory.")
        print("First, run 'python table_extractor.py your_file.pdf' to generate table JSON files.")
        sys.exit(0)

    print(f"Found {len(json_files)} table JSON file(s) to process.\\n")

    for json_file in json_files:
        df = load_json_to_dataframe(json_file)

        if df is not None:
            print("DataFrame successfully created:")
            print(df)

            # Demonstrate selecting a column
            if not df.columns.empty:
                first_column_name = df.columns[0]
                print(f"\\nExample of selecting the first column ('{first_column_name}'):")
                print(df[first_column_name])

        print("\n" + "="*40 + "\n")
